Week 2
andrewkakul/PostIndustria pull request #2
Opened 2020-11-20 07:14 UTC by andrewkakul

2020-11-20 14:28 UTC, debuggerUA requested changes
Не совсем правильно работает:
при клике по ссылке появляется выбор программы для просмотра, а нужно чтобы твоя активити открывалась автоматически. Напиши в комменты как можно это сделать.

2020-11-20 14:28 UTC, debuggerUA commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".ui.SecondActivity">
Дай этой активити более понятное название.
Их потом будет ещё много.

2020-11-20 14:28 UTC, debuggerUA commented on app/src/main/java/com/example/postindustriaandroid/ui/MainActivity.kt
> +        const val FLICK_PHOTO_BASE_URL = "https://www.flickr.com/photos/"
Активити - это способ представления информации.
В них не хранят url, какие-то настройки и так далее.
Убери это в другой класс.

2020-11-20 14:28 UTC, debuggerUA commented on app/src/main/java/com/example/postindustriaandroid/ui/MainActivity.kt
> +        for(i in 0 until sizeOfList){
`element.photos.photo.forEach { ... }`

2020-11-20 14:28 UTC, debuggerUA commented on app/src/main/java/com/example/postindustriaandroid/ui/MainActivity.kt
> +            textToView = textToView +
Строки в java немутабельны, для построения строк используй *StringBuilder*

2020-11-20 14:28 UTC, debuggerUA commented on app/src/main/java/com/example/postindustriaandroid/ui/SecondActivity.kt
> +        val intent = intent
В чём смысл новой переменной?

2020-11-20 14:28 UTC, debuggerUA commented on app/src/main/java/com/example/postindustriaandroid/ui/SecondActivity.kt
> +        if (path0.isEmpty()) {
Что это за остатки древней цивилизации? =)

2020-11-20 14:28 UTC, debuggerUA commented on app/src/main/java/com/example/postindustriaandroid/ui/SplashScreenActivity.kt
> +class SplashScreenActivity : AppCompatActivity() {
Не лучший способ.
На быстрых устройствах эту активити будет не видно - слишкой быстро скроется.
Подумай и напиши в коммент как можно сделать по-другому.

2020-11-20 14:28 UTC, debuggerUA commented on app/src/main/res/layout/activity_main.xml
> +        android:text="@string/your_text"
```suggestion
        android:hint="@string/your_text"
```

2020-11-20 14:33 UTC, andrewkakul commented on app/src/main/java/com/example/postindustriaandroid/ui/SplashScreenActivity.kt
> +class SplashScreenActivity : AppCompatActivity() {
Можно реализовать через запуск как активити, с таймером

2020-11-20 14:39 UTC, debuggerUA commented on app/src/main/java/com/example/postindustriaandroid/ui/SplashScreenActivity.kt
> +class SplashScreenActivity : AppCompatActivity() {
Будет работать, но как-то некрасиво что-ли добавлять таймер.
А ещё как?

2020-11-20 15:13 UTC, andrewkakul commented on app/src/main/java/com/example/postindustriaandroid/ui/SplashScreenActivity.kt
> +class SplashScreenActivity : AppCompatActivity() {
Если честно, затрудняюсь ответить. Знаю только два способа: через background, и непосредственно с помощью таймера.

2020-11-20 15:14 UTC, andrewkakul commented on app/src/main/java/com/example/postindustriaandroid/ui/MainActivity.kt
> +        for(i in 0 until sizeOfList){
По этому вопросу написал в телеграм.

2020-11-20 15:18 UTC, andrewkakul commented
Ответил в телеграм

2020-11-20 18:41 UTC, andrewkakul commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".ui.SecondActivity">
Исправил

2020-11-20 18:41 UTC, andrewkakul commented on app/src/main/java/com/example/postindustriaandroid/ui/MainActivity.kt
> +        const val FLICK_PHOTO_BASE_URL = "https://www.flickr.com/photos/"
Исправил

2020-11-20 18:41 UTC, andrewkakul commented on app/src/main/java/com/example/postindustriaandroid/ui/MainActivity.kt
> +            textToView = textToView +
Сделал

2020-11-20 18:41 UTC, andrewkakul commented on app/src/main/java/com/example/postindustriaandroid/ui/SecondActivity.kt
> +        val intent = intent
Забыл убрать

2020-11-20 18:42 UTC, andrewkakul commented on app/src/main/java/com/example/postindustriaandroid/ui/SecondActivity.kt
> +        if (path0.isEmpty()) {
Я старовер =) Но все же исправил

2020-11-20 18:42 UTC, andrewkakul commented on app/src/main/res/layout/activity_main.xml
> +        android:text="@string/your_text"
Да, забыл поменять. Уже исправил

2020-11-23 09:19 UTC, debuggerUA commented on app/src/main/java/com/example/postindustriaandroid/ui/SplashScreenActivity.kt
> +class SplashScreenActivity : AppCompatActivity() {
Разные есть подходы. Вот несколько дополнительных вариантов:
1. Использовать одну активити с android:windowBackground. То есть splash показывается только пока не загрузится основной интерфейс
2. Использовать одну активити, в которой подменяем интерфейс спустя какое-то время или после загрузки каких-то данных.

2020-11-23 09:19 UTC, debuggerUA approved these changes

2020-11-24 10:13 UTC, merged